// <auto-generated>This is auto-generated code by Validator Management Tool. Do not modify.</auto-generated>
namespace Skyline.DataMiner.CICD.Validators.Protocol.Tests.Protocol.QActions.QAction.CheckDeprecatedDllReferences
{
    using System;
    using System.Collections.Generic;

    using Skyline.DataMiner.CICD.Models.Protocol.Read;
    using Skyline.DataMiner.CICD.Validators.Common.Interfaces;
    using Skyline.DataMiner.CICD.Validators.Common.Model;
    using Skyline.DataMiner.CICD.Validators.Protocol.Common;
    using Skyline.DataMiner.CICD.Validators.Protocol.Interfaces;

    internal static class Error
    {
        public static IValidationResult DeprecatedDll(IValidate test, IReadable referenceNode, IReadable positionNode, string packageName, string qactionId)
        {
            return new ValidationResult
            {
                Test = test,
                CheckId = CheckId.CheckDeprecatedDllReferences,
                ErrorId = ErrorIds.DeprecatedDll,
                FullId = "3.44.1",
                Category = Category.QAction,
                Severity = Severity.Critical,
                Certainty = Certainty.Certain,
                Source = Source.Validator,
                FixImpact = FixImpact.NonBreaking,
                GroupDescription = "",
                Description = String.Format("Deprecated DLL '{0}' referenced. QAction '{1}'.", packageName, qactionId),
                HowToFix = "Replace the deprecated DLL by a NuGet and adapt the QAction accordingly.",
                HasCodeFix = false,

                PositionNode = positionNode,
                ReferenceNode = referenceNode,
            };
        }
    }

    internal static class ErrorIds
    {
        public const uint DeprecatedDll = 1;
    }

    /// <summary>
    /// Contains the identifiers of the checks.
    /// </summary>
    public static class CheckId
    {
        /// <summary>
        /// The check identifier.
        /// </summary>
        public const uint CheckDeprecatedDllReferences = 44;
    }
}