namespace Validator_Management_Tool.Common
{
    using System.Collections.Immutable;

    /// <summary>
    /// Static class that holds the settings.
    /// </summary>
    public static class Settings
    {
        // The default paths
        public const string DefaultErrorMessagesPath = "../../../../Protocol/";
        public const string DefaultTestPath = "../../../../Protocol/";
        public const string DefaultUnitTestPath = "../../../../ProtocolTests/";
        public const string DefaultXmlPath = "../../../../Protocol/ErrorMessages.xml";
        public const string DefaultExportPath = "";
        public const string DefaultExportFile = "Validator Error Messages";

        public const bool DefaultErrorClassesInOneFile = false;

        // The path specified in the settings menu
        public static string DocumentationMarkdownFilesPath = "../../../../Documentation/";
        public static string ErrorMessagesPath = "../../../../Protocol/";
        public static string TestPath = "../../../../Protocol/";
        public static string UnitTestPath = "../../../../ProtocolTests/";
        public static string XmlPath = "../../../../Protocol/ErrorMessages.xml";
        public static string ExportPath = "";
        public static string ExportFile = "Validator Error Messages";

        public static bool ErrorClassesInOneFile = false;

        public static readonly ImmutableList<string> ForbiddenStrings = ImmutableList.Create(
            "namespace",
            "Namespace",
            "class",
            "public",
            "private",
            "param",
            "string",
            "int",
            "bool",
            "uint",
            "internal",
            "protected",
            "static",
            "readonly",
            "const",
            "short",
            "long",
            "float",
            "double",
            "if",
            "else",
            "for",
            "foreach",
            "default",
            "case",
            "switch",
            "break",
            "return",
            "try",
            "catch",
            "while",
            "throw",
            "do",
            "finally",
            "as",
            "in",
            "enum",
            "equals",
            "true",
            "false",
            "lock",
            "nameof",
            "typeof",
            "new",
            "null",
            "object",
            "byte",
            "sbyte",
            "sizeof",
            "struct",
            "ulong",
            "unsafe",
            "volatile",
            "base",
            "abstract",
            "char",
            "checked",
            "continue",
            "decimal",
            "delegate",
            "event",
            "explicit",
            "extern",
            "fixed",
            "goto",
            "implicit",
            "interface",
            "operator",
            "out",
            "override",
            "params",
            "ref",
            "sealed",
            "stackalloc",
            "this",
            "unchecked",
            "unsafe",
            "ushort",
            "using static",
            "virtual",
            "Error",
            "ErrorId",
            "Validator",
            "Fix",
            "test",
            "node",
            "ExportManager",
            "Settings",
            "TestGenerator",
            "XMLParser",
            "MyCommand",
            "MyTCommand",
            "Check",
            "Serializer",
            "XmlClasses",
            "Check",
            "InputParameter",
            "InputParameters",
            "DescriptionTemplate",
            "DescriptionTemplates",
            "ErrorMessage",
            "ErrorMessages",
            "Checks",
            "Category",
            "Categories",
            "Severity",
            "Certainty",
            "ValidationChecks",
            "ErrorMessagesClass",
            "TestClass",
            "UnitTestClass",
            "EmptyStringToBooleanConvert",
            "InverterConverter",
            "CertaintyConverter",
            "CategoryConverter",
            "ArrayToStringConverter",
            "CheckIdConverter",
            "CheckBubbelUpConverter",
            "NamespaceBubbelUpConverter",
            "CategoryBubbelUpConverter",
            "AddCheckView",
            "AddCheckViewModel",
            "CheckEditView",
            "CheckEditViewModel",
            "CheckViewModel",
            "CheckView",
            "MainWindow",
            "MainWindowViewModel",
            "NewCheckView",
            "NewCheckViewModel",
            "NewNamespaceView",
            "NewNamespaceViewModel",
            "SettingsView",
            "SettingsViewModel",
            "ViewModelLocator",
            "BindableBase",
            "CodeFixContent",
            "TestAttribute",
            "TestCategory",
            "TestDescription",
            "ValidationResult",
            "ValidatorContext",
            "ProtocolAdditions",
            "ICodeFix",
            "ITest",
            "IValidationResult",
            "IValidator");
    }
}