// <auto-generated>
// Do not change. Treat this as auto-generated code as this is converted from code in DataMiner.
// If there are software changes this allows easier comparison.
// </auto-generated>
namespace Skyline.DataMiner.CICD.Validators.Protocol.Helpers.Conditions
{
    enum ConditionOperator
    {
        Undefined = 0,
        And = 1,
        Or = 2,
        Equal = 3,
        NotEqual = 4,
        GreaterThan = 5,
        GreaterThanOrEqual = 6,
        LessThan = 7,
        LessThanOrEqual = 8,
        ExclusiveOr = 9,
        Plus = 10,
        Minus = 11,
        Multiply = 12,
        Divide = 13
    }
}