// <auto-generated>
// Do not change. Treat this as auto-generated code as this is converted from code in DataMiner.
// If there are software changes this allows easier comparison.
// </auto-generated>
namespace SLDisValidator2.Helpers.Conditions
{
    class Variant
    {
        public Variant()
        {
            Type = VariantType.VT_EMPTY;
        }

        public VariantType Type { get; set; }

        public string StringValue { get; set; }
        public double? DoubleValue { get; set; }

        public bool? BooleanValue { get; set; }
    }
}