name: Export Error Messages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events.
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+-**"
      - "[0-9]+.[0-9]+.[0-9]+-**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  export:
    name: Export Error Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install NuGetToggleOnBuild
        run: dotnet tool install Skyline.DataMiner.CICD.Tools.NuGetToggleOnBuild --global
                
      - name: Disable NuGet Creation on Subsequent Builds
        run: NuGetToggleOnBuild --setToActive false --workspace ${{ github.workspace }} --onlyOnConfiguredNuGet false

      - name: Building
        run: dotnet build "./ExportErrorMessages/ExportErrorMessages.csproj" --configuration Release -nodeReuse:false

      - name: Run export logic
        run: | 
          ./ExportErrorMessages ${{ github.workspace }}/Protocol/ErrorMessages.xml ${{ github.ref_name }} ${{ github.workspace }}/TEMP
        working-directory: ${{ github.workspace }}/ExportErrorMessages/bin/Release/net8.0

      - uses: actions/upload-artifact@v4
        with:
          name: Error Messages
          path: ${{ github.workspace }}/TEMP/Validator Error Messages - ${{ github.ref_name }}.xlsx
